# This is a basic workflow that is manually triggered

name: Manual model run

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: "INFO"
      samples:
        description: 'Number of samples to draw'
        required: true
        default: 1000
      burn_in:
        description: 'Number of burn in steps'
        required: true
        default: 1000

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # We use multiple jobs 
  setup:
    # The type of runner that the job will run on
    runs-on: tur007

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          #
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: 'recursive'
      
      # Setup python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
  run:
    needs: [setup]
    runs-on: tur007
    steps:
      - name: Data retrieval
        working-directory: ./scripts/data_generators
        run: python Germany_bundesländer.py
      - name: Model run & Plots
        working-directory: ./scripts
        run: python run_Germany_bundesländer.py --samples ${{ github.event.inputs.samples }} --burn_in ${{ github.event.inputs.burn_in }} --verbosity ${{ github.event.inputs.logLevel }}
        
